ALTER TYPE "session_status" ADD VALUE 'waiting_for_documents' BEFORE 'summarizing';--> statement-breakpoint
CREATE TABLE "mcp_tokens" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
	"user_id" text NOT NULL UNIQUE,
	"token_hash" text NOT NULL UNIQUE,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"last_used_at" timestamp,
	"revoked_at" timestamp
);
--> statement-breakpoint
CREATE TABLE "effect_mq_job_attempts" (
	"job_id" text,
	"attempt" integer,
	"outcome" text NOT NULL,
	"started_at" timestamp with time zone,
	"finished_at" timestamp with time zone NOT NULL,
	"exit" jsonb,
	CONSTRAINT "effect_mq_job_attempts_pkey" PRIMARY KEY("job_id","attempt")
);
--> statement-breakpoint
CREATE TABLE "effect_mq_dedupe" (
	"name" text,
	"key" text,
	"job_id" text NOT NULL,
	"window_expires_at" timestamp with time zone,
	CONSTRAINT "effect_mq_dedupe_pkey" PRIMARY KEY("name","key")
);
--> statement-breakpoint
CREATE TABLE "effect_mq_flow_children" (
	"flow_id" text,
	"child_key" text,
	"name" text NOT NULL,
	"store_key" text NOT NULL,
	"spec" jsonb NOT NULL,
	"status" text NOT NULL,
	"exit" jsonb,
	"failed_reason" text,
	"cascaded" boolean NOT NULL,
	"pending_since" timestamp with time zone NOT NULL,
	CONSTRAINT "effect_mq_flow_children_pkey" PRIMARY KEY("flow_id","child_key")
);
--> statement-breakpoint
CREATE TABLE "effect_mq_flow_outbox" (
	"id" bigserial PRIMARY KEY,
	"flow_name" text NOT NULL,
	"parent_store_key" text NOT NULL,
	"report" jsonb NOT NULL
);
--> statement-breakpoint
CREATE TABLE "effect_mq_queue_control" (
	"queue" text PRIMARY KEY,
	"paused" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
CREATE TABLE "effect_mq_schedules" (
	"key" text PRIMARY KEY,
	"job_name" text NOT NULL,
	"queue" text NOT NULL,
	"cron" text,
	"tz" text,
	"every_ms" bigint,
	"payload" jsonb,
	"metadata" jsonb DEFAULT '{}' NOT NULL,
	"priority" integer DEFAULT 0 NOT NULL,
	"attempts_max" integer NOT NULL,
	"backoff" jsonb,
	"keep" jsonb,
	"timeout_ms" bigint,
	"group_name" text,
	"next_run_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "effect_mq_jobs" (
	"id" text PRIMARY KEY,
	"name" text NOT NULL,
	"queue" text NOT NULL,
	"state" text NOT NULL,
	"priority" integer DEFAULT 0 NOT NULL,
	"seq" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "effect_mq_jobs_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"payload" jsonb,
	"metadata" jsonb DEFAULT '{}' NOT NULL,
	"attempts_max" integer NOT NULL,
	"attempts_made" integer DEFAULT 0 NOT NULL,
	"stalled_count" integer DEFAULT 0 NOT NULL,
	"backoff" jsonb,
	"keep" jsonb,
	"timeout_ms" bigint,
	"cancel_requested" boolean DEFAULT false NOT NULL,
	"dedupe_key" text,
	"trace" jsonb,
	"parent" jsonb,
	"flow_fail_fast" boolean,
	"flow_pending" integer,
	"flow_completed" integer,
	"flow_failed" integer,
	"flow_cancelled" integer,
	"run_at" timestamp with time zone NOT NULL,
	"enqueued_at" timestamp with time zone NOT NULL,
	"processed_at" timestamp with time zone,
	"finished_at" timestamp with time zone,
	"exit" jsonb,
	"failed_reason" text,
	"lock_token" text,
	"lock_expires_at" timestamp with time zone
);
--> statement-breakpoint
DROP TABLE "queue_messages";--> statement-breakpoint
ALTER TABLE "agent_sessions" ADD COLUMN "error_reason" text;--> statement-breakpoint
CREATE INDEX "effect_mq_flow_children_pending_idx" ON "effect_mq_flow_children" ("pending_since") WHERE "status" = 'pending';--> statement-breakpoint
CREATE INDEX "effect_mq_flow_children_cascade_idx" ON "effect_mq_flow_children" ("flow_id") WHERE "status" = 'cancelled' AND NOT "cascaded";--> statement-breakpoint
CREATE INDEX "effect_mq_schedules_due_idx" ON "effect_mq_schedules" ("next_run_at");--> statement-breakpoint
CREATE INDEX "effect_mq_jobs_ready_idx" ON "effect_mq_jobs" ("queue","priority" DESC NULLS LAST,"seq") WHERE "state" = 'waiting';--> statement-breakpoint
CREATE INDEX "effect_mq_jobs_delayed_idx" ON "effect_mq_jobs" ("queue","run_at") WHERE "state" = 'delayed';--> statement-breakpoint
CREATE INDEX "effect_mq_jobs_active_idx" ON "effect_mq_jobs" ("lock_expires_at") WHERE "state" = 'active';--> statement-breakpoint
CREATE INDEX "effect_mq_jobs_history_idx" ON "effect_mq_jobs" ("name","state","finished_at");--> statement-breakpoint
CREATE INDEX "effect_mq_jobs_listing_idx" ON "effect_mq_jobs" ("enqueued_at" DESC NULLS LAST,"id" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "effect_mq_jobs_metadata_idx" ON "effect_mq_jobs" USING gin ("metadata" jsonb_path_ops);--> statement-breakpoint
ALTER TABLE "mcp_tokens" ADD CONSTRAINT "mcp_tokens_user_id_users_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "effect_mq_job_attempts" ADD CONSTRAINT "effect_mq_job_attempts_job_id_effect_mq_jobs_id_fkey" FOREIGN KEY ("job_id") REFERENCES "effect_mq_jobs"("id") ON DELETE CASCADE;--> statement-breakpoint
DROP TYPE "queue_message_status";