/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsSessionIdQuestionsRouteImport } from './routes/sessions/$sessionId/questions'
import { Route as SessionsSessionIdOutputRouteImport } from './routes/sessions/$sessionId/output'
import { Route as SessionsSessionIdDebugRouteImport } from './routes/sessions/$sessionId/debug'
import { Route as SessionsSessionIdConfirmRouteImport } from './routes/sessions/$sessionId/confirm'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdQuestionsRoute =
  SessionsSessionIdQuestionsRouteImport.update({
    id: '/sessions/$sessionId/questions',
    path: '/sessions/$sessionId/questions',
    getParentRoute: () => rootRouteImport,
  } as any)
const SessionsSessionIdOutputRoute = SessionsSessionIdOutputRouteImport.update({
  id: '/sessions/$sessionId/output',
  path: '/sessions/$sessionId/output',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdDebugRoute = SessionsSessionIdDebugRouteImport.update({
  id: '/sessions/$sessionId/debug',
  path: '/sessions/$sessionId/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdConfirmRoute =
  SessionsSessionIdConfirmRouteImport.update({
    id: '/sessions/$sessionId/confirm',
    path: '/sessions/$sessionId/confirm',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sessions/$sessionId/confirm': typeof SessionsSessionIdConfirmRoute
  '/sessions/$sessionId/debug': typeof SessionsSessionIdDebugRoute
  '/sessions/$sessionId/output': typeof SessionsSessionIdOutputRoute
  '/sessions/$sessionId/questions': typeof SessionsSessionIdQuestionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sessions/$sessionId/confirm': typeof SessionsSessionIdConfirmRoute
  '/sessions/$sessionId/debug': typeof SessionsSessionIdDebugRoute
  '/sessions/$sessionId/output': typeof SessionsSessionIdOutputRoute
  '/sessions/$sessionId/questions': typeof SessionsSessionIdQuestionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sessions/$sessionId/confirm': typeof SessionsSessionIdConfirmRoute
  '/sessions/$sessionId/debug': typeof SessionsSessionIdDebugRoute
  '/sessions/$sessionId/output': typeof SessionsSessionIdOutputRoute
  '/sessions/$sessionId/questions': typeof SessionsSessionIdQuestionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sessions/$sessionId/confirm'
    | '/sessions/$sessionId/debug'
    | '/sessions/$sessionId/output'
    | '/sessions/$sessionId/questions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sessions/$sessionId/confirm'
    | '/sessions/$sessionId/debug'
    | '/sessions/$sessionId/output'
    | '/sessions/$sessionId/questions'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/sessions/$sessionId/confirm'
    | '/sessions/$sessionId/debug'
    | '/sessions/$sessionId/output'
    | '/sessions/$sessionId/questions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SessionsSessionIdConfirmRoute: typeof SessionsSessionIdConfirmRoute
  SessionsSessionIdDebugRoute: typeof SessionsSessionIdDebugRoute
  SessionsSessionIdOutputRoute: typeof SessionsSessionIdOutputRoute
  SessionsSessionIdQuestionsRoute: typeof SessionsSessionIdQuestionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId/questions': {
      id: '/sessions/$sessionId/questions'
      path: '/sessions/$sessionId/questions'
      fullPath: '/sessions/$sessionId/questions'
      preLoaderRoute: typeof SessionsSessionIdQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId/output': {
      id: '/sessions/$sessionId/output'
      path: '/sessions/$sessionId/output'
      fullPath: '/sessions/$sessionId/output'
      preLoaderRoute: typeof SessionsSessionIdOutputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId/debug': {
      id: '/sessions/$sessionId/debug'
      path: '/sessions/$sessionId/debug'
      fullPath: '/sessions/$sessionId/debug'
      preLoaderRoute: typeof SessionsSessionIdDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId/confirm': {
      id: '/sessions/$sessionId/confirm'
      path: '/sessions/$sessionId/confirm'
      fullPath: '/sessions/$sessionId/confirm'
      preLoaderRoute: typeof SessionsSessionIdConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SessionsSessionIdConfirmRoute: SessionsSessionIdConfirmRoute,
  SessionsSessionIdDebugRoute: SessionsSessionIdDebugRoute,
  SessionsSessionIdOutputRoute: SessionsSessionIdOutputRoute,
  SessionsSessionIdQuestionsRoute: SessionsSessionIdQuestionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
