/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsIdQuestionsRouteImport } from './routes/sessions/$id/questions'
import { Route as SessionsIdOutputRouteImport } from './routes/sessions/$id/output'
import { Route as SessionsIdConfirmRouteImport } from './routes/sessions/$id/confirm'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIdQuestionsRoute = SessionsIdQuestionsRouteImport.update({
  id: '/sessions/$id/questions',
  path: '/sessions/$id/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIdOutputRoute = SessionsIdOutputRouteImport.update({
  id: '/sessions/$id/output',
  path: '/sessions/$id/output',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIdConfirmRoute = SessionsIdConfirmRouteImport.update({
  id: '/sessions/$id/confirm',
  path: '/sessions/$id/confirm',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sessions/$id/confirm': typeof SessionsIdConfirmRoute
  '/sessions/$id/output': typeof SessionsIdOutputRoute
  '/sessions/$id/questions': typeof SessionsIdQuestionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sessions/$id/confirm': typeof SessionsIdConfirmRoute
  '/sessions/$id/output': typeof SessionsIdOutputRoute
  '/sessions/$id/questions': typeof SessionsIdQuestionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sessions/$id/confirm': typeof SessionsIdConfirmRoute
  '/sessions/$id/output': typeof SessionsIdOutputRoute
  '/sessions/$id/questions': typeof SessionsIdQuestionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sessions/$id/confirm'
    | '/sessions/$id/output'
    | '/sessions/$id/questions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sessions/$id/confirm'
    | '/sessions/$id/output'
    | '/sessions/$id/questions'
  id:
    | '__root__'
    | '/'
    | '/sessions/$id/confirm'
    | '/sessions/$id/output'
    | '/sessions/$id/questions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SessionsIdConfirmRoute: typeof SessionsIdConfirmRoute
  SessionsIdOutputRoute: typeof SessionsIdOutputRoute
  SessionsIdQuestionsRoute: typeof SessionsIdQuestionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$id/questions': {
      id: '/sessions/$id/questions'
      path: '/sessions/$id/questions'
      fullPath: '/sessions/$id/questions'
      preLoaderRoute: typeof SessionsIdQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$id/output': {
      id: '/sessions/$id/output'
      path: '/sessions/$id/output'
      fullPath: '/sessions/$id/output'
      preLoaderRoute: typeof SessionsIdOutputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$id/confirm': {
      id: '/sessions/$id/confirm'
      path: '/sessions/$id/confirm'
      fullPath: '/sessions/$id/confirm'
      preLoaderRoute: typeof SessionsIdConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SessionsIdConfirmRoute: SessionsIdConfirmRoute,
  SessionsIdOutputRoute: SessionsIdOutputRoute,
  SessionsIdQuestionsRoute: SessionsIdQuestionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
